import './globals.css'
import '@/public/css/animate.min.css'
import '@/public/css/bootstrap.min.css'
import '@/public/css/flaticon.css'
import '@/public/css/fontawesome.min.css'
import '@/public/css/magnific-popup.min.css'
import '@/public/css/meanmenu.css'
import '@/public/css/nice-select.min.css'
import '@/public/css/owl.carousel.min.css'
import '@/public/css/responsive.css'
import '@/public/css/style.css'
import '@/public/css/swiper.min.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Rebit',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
